# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f930163c64dd98cdf185d1e453ca371d6e0fe441063032160308908a3618a6e2f6a80d938547aaee69257c9a60b842ed2e0bd980581219f0614025c7573c95

test:
  secret_key_base: 8ade47e91c7952ac31007a9806ed20b3512c61517faa9228dadbb42ccc52c8df23c53e18dee119ce2792fceed27191cef95854f6a24856ae788b7ec0adebc646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
